### ISSUE TITLE
Php Process Error on latest version

### ISSUE THREAD

**Issue by fmarcoux96** [ateodorescu/home-assistant-addons#10]
Currently having an issue where none of my servers are loading properly. Did the updates to the addon and the HACS integration and it doesn't work.

`2024/03/14 07:20:18 [error] 205#205: *1 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessSignaledException: "The process has been signaled with signal "11"." at /app/vendor/symfony/process/Process.php line 436" while reading response header from upstream, client: 172.30.32.1, server: _, request: "GET /?host=192.168.1.21&port=623&user=root&password=calvin HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:9595"`

trying to monitor Dell iDRAC.

**Comment by ateodorescu** [comment]
What do you get when you run the following command?
`ipmitool -H YOUR_SERVER -p 623 -U root -P calvin -I lanplus sensor`

**Comment by corgan2222** [comment]
same here. Thanks for the https://github.com/ateodorescu/home-assistant-addons/issues/9#issuecomment-1996947641 fix, but now I get this error.

> 2024/03/14 22:52:16 [error] 205#205: *3 FastCGI sent in stderr: "PHP message: Error occurred when running "ipmitool -H 192.168.2.2 -p 623 -U root -P #### -I lanplus dcmi power reading".

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/52538f84-b0f7-45a6-b2a1-5d85097c6b34)


on the console:
`ipmitool -I lanplus -H 192.168.2.2 -U root -P $pfpw sensor`

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/61e21307-b256-4034-82c2-e1b96701fe8e)

IPMI Tools Server Addon: 1.2.0 
HA Connector: 1.5.0
Server: [Dell PowerEdge R210 II](https://i.dell.com/sites/csdocuments/Business_solutions_engineering-Docs_Documents/de/at/r210-2-spec-sheet-de.pdf)
[iDRAC6 IPMI-Version 2.0](https://www.dell.com/support/kbdoc/en-en/000123577/set-up-and-manage-idrac-6-lifecycle-controller-for-dell-poweredge-11g-servers?lang=en)

**Comment by MwC-Trexx** [comment]
Seeing similar behavior with Dell PowerEdge R630

`2024/03/14 22:20:45 [error] 206#206: *107 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessSignaledException: "The process has been signaled with signal "11"." at /app/vendor/symfony/process/Process.php line 436" while reading response header from upstream, client: 172.30.32.1, server: _, request: "GET /?host=10.10.20.11&port=623&user=root&password=#####&interface=lanplus HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: `"localhost:9595"`

IMPI Tool Addon: v1.2.0
HA IPMI Integration: v1.5.0 (also has connection issues w/v1.4.0)
Server: Dell PowerEdge R630
iDrac v8 FW: 2.85.85.85
IPMI Version: 2.0

FYI - running IPMI Tool (v1.8.19 via brew) on Mac works properly.  
`ipmitool -H 10.10.20.11 -p 623 -U root -P ### -I lanplus sdr elist`

**Comment by ateodorescu** [comment]
I guess Dell servers do not support this command `ipmitool -I lanplus -H SERVER_IP -U USER -P PASSWORD dcmi power reading`. Maybe this command should run in a try/catch block and ignore it if it fails. On my microserver that command does not fail.

**Comment by corgan2222** [comment]
> I guess Dell servers do not support this command `ipmitool -I lanplus -H SERVER_IP -U USER -P PASSWORD dcmi power reading`. Maybe this command should run in a try/catch block and ignore it if it fails. On my microserver that command does not fail.

I can confirm, this command does not exist.
![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/82a09e22-c278-44e4-a7cd-f697edf48f2e)

try/catch is always a good Idea. :)
Hit me, if you need a beta tester.

**Comment by chunkster29** [comment]
i have a dell R720 thats supports - ipmitool -I lanplus -H SERVER_IP -U USER -P PASSWORD dcmi power reading and also have a R710 that does not so it depends on the server whether or not it works sdr elist or sensor both work for the R710 i think would a good solution would be not hard coding the commands in addon but lets the user choose which commands work for them

**Comment by ateodorescu** [comment]
@corgan2222 Would you please grab the latest code of the addon and check if it runs on your HASS server? Thanks!

**Comment by ateodorescu** [comment]
@chunkster29 Would you also please grab the latest code of the addon and try it out? Thanks!

**Comment by chunkster29** [comment]
I'm using the lastest code thats whats cousing the error ver 1.1.25 works fine

**Comment by ateodorescu** [comment]
> I'm using the lastest code thats whats cousing the error ver 1.1.25 works fine

I have updated the addon half an hour ago. Would you please grab the latest code (1.2.1) and test it out? Thanks!

**Comment by corgan2222** [comment]
I found the ipmi-server in 
/usr/share/hassio/addons/git/304fecf0/
and uploaded the whole directory.
cat config.yml shows correct the 1.2.1

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/7ce984ac-a9c7-4962-89c4-792c2f7e08c7)

But in the Addons Page and in the logs, Im still on 1.2.0??
![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/79dc44c7-83e1-4dce-9df8-618b5b57de63)

So how to update on a supervised installation?

**Comment by ateodorescu** [comment]
![Screenshot 2024-03-15 at 17 45 03](https://github.com/ateodorescu/home-assistant-addons/assets/1575894/448af75c-155e-4eb3-9748-0a8e470fc0c0)
click on that icon from top right and then it will look like this:
![Screenshot 2024-03-15 at 17 47 16](https://github.com/ateodorescu/home-assistant-addons/assets/1575894/ad46675c-6c69-45c3-88ee-94db3be9f154)

after that you open ipmitool server addon and do the update

![Screenshot 2024-03-15 at 17 47 24](https://github.com/ateodorescu/home-assistant-addons/assets/1575894/827560d4-617a-423b-883e-f96f86d83271)

**Comment by memphisdj** [comment]
Trying to readd the integration with the latest addon and getting the following 

Server is dell 720xd 

I've redacted username and password.

Hass shows failed to connect.

Tried with IP and localhost for the addon, same result. 

2024/03/15 18:08:55 [error] 205#205: *5 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessSignaledException: "The process has been signaled with signal "11"." at /app/vendor/symfony/process/Process.php line 436" while reading response header from upstream, client: 10.0.10.10, server: _, request: "GET /?host=192.168.10.10&port=623&user=&password= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.10.10:9595"

**Comment by ateodorescu** [comment]
> Trying to readd the integration with the latest addon and getting the following
> 
> Server is dell 720xd
> 
> I've redacted username and password.
> 
> Hass shows failed to connect.
> 
> Tried with IP and localhost for the addon, same result.
> 
> 2024/03/15 18:08:55 [error] 205#205: *5 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\Process\Exception\ProcessSignaledException: "The process has been signaled with signal "11"." at /app/vendor/symfony/process/Process.php line 436" while reading response header from upstream, client: 10.0.10.10, server: _, request: "GET /?host=192.168.10.10&port=623&user=&password= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "10.0.10.10:9595"

addon has version 1.2.1?

**Comment by memphisdj** [comment]
![Screenshot_20240315_182151_Home Assistant.jpg](https://github.com/ateodorescu/home-assistant-addons/assets/12535078/7bdd8b35-f84d-48f2-813b-8ce223148112)

Yes, as I said, the latest. I saw your previous comment and updated it, before posting.

**Comment by corgan2222** [comment]
sadly this didn't worked out with 1.2.1.

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/8022a76d-b12b-4847-b945-0958a1f5f7ed)

The I stopped the addon, edited the IpmiController.php and rebuild the docker

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/0a43f5cb-7983-4382-9095-bbe3b64ef896)

I still get a lot of errors, but at least I get data.

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/47dfbe5c-bbe6-4c8c-8d03-a506ce08ab5f)
![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/0f4cebd9-0296-462a-ab11-b4b8b673f0fd)

Thanks, Greetz Stefan

**Comment by ateodorescu** [comment]
Thanks for the feedback. I have updated the addon again - version 1.2.2. If anyone is interested in testing the latest, I would appreciate it.
Thanks!

**Comment by memphisdj** [comment]
> Thanks for the feedback. I have updated the addon again - version 1.2.2. If anyone is interested in testing the latest, I would appreciate it.
> Thanks!

Just updated, exactly the same error.

**Comment by corgan2222** [comment]
Same for me :/
@ateodorescu I write you a PM.

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/dc770217-ffde-43e9-b8dc-f61213f22a06)

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/d87a6e0a-9d48-4b8f-b4d1-165be0ff93bd)

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/45786117-ddfa-4906-8752-099ac4fe9b16)

**Comment by chunkster29** [comment]
I can confirm it's working on my r710

**Comment by ateodorescu** [comment]
A new update for the addon is available: 1.2.5
Please try it out and let me know if it works for you!
Thanks!

**Comment by memphisdj** [comment]
![Screenshot_20240315_193627_Home Assistant.jpg](https://github.com/ateodorescu/home-assistant-addons/assets/12535078/233bfbc9-cc82-4bfd-ad87-d85586476390)

And same error as before.

**Comment by MwC-Trexx** [comment]
> A new update for the addon is available: 1.2.5 Please try it out and let me know if it works for you! Thanks!

Different message from add-on launch:
```
2024/03/15 14:14:32 [error] 205#205: *147 FastCGI sent in stderr: "PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.0.20:8123"
```

Still seeing same issues from IPMI Connector v1.2 when trying to do a Dell R630 server add:
```
2024/03/15 14:18:28 [error] 205#205: *157 FastCGI sent in stderr: "PHP message: Error occurred when running "ipmitool -H 10.10.20.11 -p 623 -U root -P #### -I lanplus sensor".
The process has been signaled with signal "11"" while reading response header from upstream, client: 172.30.32.1, server: _, request: "GET /?host=10.10.20.11&port=623&user=root&password=####&interface=lanplus HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:9595"
```

Seeing same error when trying to perform SDR elist from within the IMPI Server v1.2.5 add-on:
```
Fatal PCI SSD Er | 3Ah | ns  | 34.1 | No Reading
Segmentation fault (core dumped)
root@304fecf0-ipmi-server:/$ 
```

**Comment by ateodorescu** [comment]
Just updated the addon to version 1.2.7. Please test it out. Let's see if the "sdr list full" command works better than "sensor" command. Thanks!

**Comment by memphisdj** [comment]
> Just updated the addon to version 1.2.7. Please test it out. Let's see if the "sdr list full" command works better than "sensor" command. Thanks!

![Screenshot_20240316_105728_Home Assistant.jpg](https://github.com/ateodorescu/home-assistant-addons/assets/12535078/897f2f84-e3ad-4bbb-9077-99be8988d1e2)

The latest one, works like a charm. Thank you for your time and effort.

**Comment by corgan2222** [comment]
1.27 works perfectly!! Awesome Job Adrian! Thanks a lot!

**Comment by ateodorescu** [comment]
@MwC-Trexx, @fmarcoux96 Does the latest version of addon 1.2.7 work for you?
Thanks!

**Comment by fmarcoux96** [comment]
> @MwC-Trexx, @fmarcoux96 Does the latest version of addon 1.2.7 work for you? Thanks!

Seems like it! Thanks a lot! Sorry haven't been useful, too busy to play around with it recently.
