### ISSUE TITLE
Error: No hostname provided

### ISSUE THREAD

**Issue by enkay97** [ateodorescu/home-assistant-addons#12]
Hi all

{"success":false,"message":"Wrong connection data provided!","debug":"No hostname provided!\nNo hostname provided!\nNo hostname provided!\nNo hostname provided!"}

`
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting

 Add-on: IPMItool server
 IPMItool server
 Add-on version: 1.2.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 12.1  (amd64 / qemux86-64)
 Home Assistant Core: 2024.3.1
 Home Assistant Supervisor: 2024.03.0

 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.

s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun nginx (no readiness notification)
services-up: info: copying legacy longrun php-fpm (no readiness notification)
[19:45:53] INFO: Starting PHP-FPM...
s6-rc: info: service legacy-services successfully started
[19:45:53] INFO: Starting NGinx...
2024/03/15 19:45:57 [error] 205#205: *3 FastCGI sent in stderr: "PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mydomian.xx", referrer: "https://mydomian.xx/hassio"
2024/03/15 19:50:26 [error] 205#205: *15 FastCGI sent in stderr: "PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!PHP message: No hostname provided!" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mydomian.xx", referrer: 

"https://mydomian.xx/hassio"

`

where to set a hostname?

version is 1.2.5

thank you for support!

**Comment by ateodorescu** [comment]
Please test the latest version 1.2.7. Thanks!

**Comment by enkay97** [comment]
Thank you, it's solved :)
