### ISSUE TITLE
IPMI server wont return any sensors

### ISSUE THREAD

**Issue by knifesk** [ateodorescu/home-assistant-addons#2]
While debugging it I found the problem. This double negation prevents the sensors command to run, so, no sensor data.

https://github.com/ateodorescu/home-assistant-addons/blob/c76007b9bffea93160082741e516c549ac8a750b/ipmi-server/rootfs/app/src/Controller/IpmiController.php#L319

I can make a PR, but I think it will be much faster if you push that little fix.

Cheers!

**Comment by ateodorescu** [comment]
@knifesk, thank you! I have fixed the typo. Such a newbie mistake! :)
