### ISSUE TITLE
Failed to install add-on

### ISSUE THREAD

**Issue by ahmadnassri** [ateodorescu/home-assistant-addons#5]
fails to install with the following error:

```
The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xml php$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 1
```

**Comment by Redblockmasteur** [comment]
Hi i'm experiencing the same issue but the error message is different.
`The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xmlphp$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 1`

**Comment by SThomae** [comment]
Hi, same problem with my installation.

The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xml php$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 1

Core                          2023.11.0
Supervisor                2023.10.1
Operating System    11.1
Frontend                  20231030.1
IPMI-Server Version 1.1.15

**Comment by Sperryfreak01** [comment]
Same issue here. 

The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xml php$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 1

**Comment by frangigu** [comment]
Same for me too

**Comment by SThomae** [comment]
Still the same problem after updating HA.

The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xml php$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 1

Core 2023.11.1
Supervisor 2023.11.0
Operating System 11.1
Frontend 20231030.1
IPMI-Server Version 1.1.15

**Comment by chouking** [comment]
The command '/bin/bash -o pipefail -c apk -U update && apk -U upgrade && apk -U add --no-cache ipmitool nginx=1.24.0-r6 php$PHPVERS php$PHPVERS-fpm php$PHPVERS-curl php$PHPVERS-dom php$PHPVERS-gettext php$PHPVERS-xml php$PHPVERS-simplexml php$PHPVERS-zip php$PHPVERS-zlib php$PHPVERS-gd php$PHPVERS-openssl php$PHPVERS-mysqli php$PHPVERS-pdo php$PHPVERS-pdo_mysql php$PHPVERS-pgsql php$PHPVERS-pdo_pgsql php$PHPVERS-sqlite3 php$PHPVERS-pdo_sqlite php$PHPVERS-json php$PHPVERS-mbstring php$PHPVERS-ctype php$PHPVERS-opcache php$PHPVERS-session php$PHPVERS-tokenizer && mkdir -p /app && mkdir /app/cache && mkdir /var/tmp/nginx' returned a non-zero code: 99

**Comment by ateodorescu** [comment]
Aparently it was not possible to fetch `nginx=1.24.0-r6` so I have changed the code to use `nginx=1.24.0-r7`.
Get the latest code and try again, please. Let me know if it works for you.

**Comment by SThomae** [comment]
Thanks for your work.
Installation of version 1.1.25 was successful.

Core 2023.11.1
Supervisor 2023.11.0
Operating System 11.1
Frontend 20231030.1
IPMI-Server Version 1.1.25
