### ISSUE TITLE
Config error due to ¨empty¨ request

### ISSUE THREAD

**Issue by frankrot** [ateodorescu/home-assistant-addons#8]
Hi,

I use a Megarac BMC, when I try to configure the ipmi connector I get a timeout. The log shows:

2024/02/02 10:36:47 [error] 205#205: *38 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 192.168.168.5, server: _, request: "GET /?host=192.168.168.207&port=623&user=admin&password=xxx HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.168.5:9595"

ipmitool also throws error: No command provided!
 
which is what I think this addon parses as connection error. It is not. When I add ¨bmc info" either to command line or to the server url it succeeds:

cli output 
Device ID                 : 32
Device Revision           : 1
Firmware Revision         : 12.61
IPMI Version              : 2.0
Manufacturer ID           : 15370
Manufacturer Name         : GIGA-BYTE TECHNOLOGY CO., LTD
Product ID                : 4106 (0x100a)
Product Name              : Unknown (0x100A)
Device Available          : yes
Provides Device SDRs      : yes
Additional Device Support :
    Sensor Device
    SDR Repository Device
    SEL Device
    FRU Inventory Device
    IPMB Event Receiver
    IPMB Event Generator
    Chassis Device
Aux Firmware Rev Info     : 
    0x11
    0x00
    0x00
    0x00

server output:

success	true
output	"Device ID                 : 32\nDevice Revision           : 1\nFirmware Revision         : 12.61\nIPMI Version              : 2.0\nManufacturer ID           : 15370\nManufacturer Name         : GIGA-BYTE TECHNOLOGY CO., LTD\nProduct ID                : 4106 (0x100a)\nProduct Name              : Unknown (0x100A)\nDevice Available          : yes\nProvides Device SDRs      : yes\nAdditional Device Support :\n    Sensor Device\n    SDR Repository Device\n    SEL Device\n    FRU Inventory Device\n    IPMB Event Receiver\n    IPMB Event Generator\n    Chassis Device\nAux Firmware Rev Info     : \n    0x11\n    0x00\n    0x00\n    0x00\n"

Could you add an optional command line to the configuration dialogue to enter the (in my case necessary) command?

**Comment by frankrot** [comment]
Seems to duplicate issue # 7...

**Comment by ateodorescu** [comment]
The latest ipmi integration 1.5.0 allows you to enter additional params that are sent to ipmi-server addon 1.2.7.
