### ISSUE TITLE
log get flooded with errors

### ISSUE THREAD

**Issue by corgan2222** [ateodorescu/home-assistant-addons#9]
Hello,

On one of my servers, the ipmi command gets a lot of errors. 
Despite this, I get the information I want, so the ipmi request works for some data.

But on each request I get these nasty error messages. Is there a way to ignore these messages?
Normally I would ignore this, but I send the logs to Loki and this mess up the log statistics. 
I tried to set the loglevel to fatal, but this did not help.

![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/0c2934f2-c7cd-4554-bcd5-71d537dde28f)

some data:
![grafik](https://github.com/ateodorescu/home-assistant-addons/assets/12233951/717a70f5-b751-4c75-ac9a-80f3a6ec1983)

thanks, greetz STefan

**Comment by ateodorescu** [comment]
Hi!

In the addon configuration did you try to change the log level?
![Screenshot 2024-02-26 at 10 46 10](https://github.com/ateodorescu/home-assistant-addons/assets/1575894/5bf99f63-c16b-42c8-b5cc-d7b0e9a1c16b)

Does it work?

Adrian

**Comment by corgan2222** [comment]
> I tried to set the loglevel to fatal, but this did not help.

I think the Problem is, that IPMI got an Error, but I can't set the log_level too none to ignore the error.

**Comment by ateodorescu** [comment]
I'm sorry but for now I can't do anything. Don't have the time to investigate this.

**Comment by corgan2222** [comment]
Ok, despite this, thanks for the answer. Will investigate this, maybe I can PR a fix.
greetz Stefan

**Comment by ateodorescu** [comment]
This is fixed in the latest version of the addon.
